version: 2

linters:
  enable:
    - govet
    - gocyclo
    - ineffassign
    - staticcheck
    - goconst
    - errcheck
    - gosec
    - misspell

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gocyclo:
    min-complexity: 30
