services:
  postgres-dev:
    image: postgres:13
    environment:
      POSTGRES_DB: encounterbrew
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
