services:
  encounterbrew-app:
    image: jaybrueder/pf2-encounterbrew:latest
    ports:
      - "8081:8081"
    depends_on:
      - encounterbrew-db
    environment:
      - PORT=8081
      - USERNAME=gamemaster
      - PASSWORD=changeme123
      - MIGRATIONS_PATH=migrations
      - DB_HOST=encounterbrew-db
      - DB_USERNAME=admin
      - DB_PASSWORD=changemetoo123
      - DB_DATABASE=encounterbrew
      - DB_URL=postgres://admin:changemetoo123@encounterbrew-db/encounterbrew?sslmode=disable
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  encounterbrew-db:
    image: postgres:13
    environment:
      POSTGRES_DB: encounterbrew
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changemetoo123
    volumes:
      - encounterbrew-db_data:/var/lib/postgresql/data

volumes:
  encounterbrew-db_data:
