FROM golang:1.23.1-alpine

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the seeder
RUN go build -o seeder cmd/seed/seeder.go

CMD ["./seeder"]
