services:
  app:
    image: jaybrueder/pf2-encounterbrew:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - USERNAME=demo
      - PASSWORD=changeme123
      - MIGRATIONS_PATH=migrations
      - DB_HOST=postgres
      - DB_USERNAME=admin
      - DB_PASSWORD=changemetoo123
      - DB_DATABASE=encounterbrew
      - DB_URL=postgres://admin:changemetoo123@postgres/encounterbrew?sslmode=disable
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: encounterbrew
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changemetoo123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
