services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=encounterbrew
      - DB_SCHEMA=public
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - prod

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://admin:admin@postgres:5432/encounterbrew?sslmode=disable", "up"]
    profiles:
      - tools

  seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=encounterbrew
      - DB_SCHEMA=public
    restart: "no"  # Don't restart the container after it finishes
    profiles:
      - seeder  # This makes the seeder not start by default

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: encounterbrew
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev

  postgres-dev:
    image: postgres:13
    environment:
      POSTGRES_DB: encounterbrew
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    profiles:
      - dev

  redis-dev:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:
