CREATE TABLE IF NOT EXISTS encounters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    party_id INTEGER REFERENCES parties(id) ON DELETE CASCADE,
    turn INTEGER NOT NULL DEFAULT 0,
    round INTEGER NOT NULL DEFAULT 0
);
