CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    level INTEGER DEFAULT 1,
    hp INTEGER DEFAULT 10,
    ac INTEGER DEFAULT 12,
    fort INTEGER DEFAULT 0,
    ref INTEGER DEFAULT 0,
    will INTEGER DEFAULT 0,
    perception INTEGER DEFAULT 0,
    party_id INTEGER REFERENCES parties(id)
);
