name: Create Release and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout & Setup ---
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # --- Logins ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Verify Docker Hub connectivity
      - name: Verify Docker Hub connectivity
        run: |
          echo "Testing Docker Hub connectivity..."
          docker pull hello-world
          docker tag hello-world ${{ secrets.DOCKERHUB_USERNAME }}/test:connectivity-test
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:connectivity-test || echo "Push test failed, but continuing..."
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/test:connectivity-test || true

      # --- Metadata ---
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jaybrueder/pf2-encounterbrew
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ !contains(github.ref, '-') && startsWith(github.ref, 'refs/tags/v') }}

      - name: Debug metadata output
        run: |
          echo "Generated tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo "Generated labels:"
          echo "${{ steps.meta.outputs.labels }}"

      # --- Build and Push ---
      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
        continue-on-error: true

      # Fallback: Try pushing each tag individually if multi-tag push failed
      - name: Push individual tags (fallback)
        if: steps.build-push.outcome == 'failure'
        run: |
          echo "Multi-tag push failed, trying individual tags..."
          TAGS="${{ steps.meta.outputs.tags }}"
          for tag in $TAGS; do
            echo "Pushing $tag..."
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              --tag "$tag" \
              --label="${{ steps.meta.outputs.labels }}" \
              . || echo "Failed to push $tag"
          done

      # --- Changelog Generation ---
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --tag ${{ github.ref_name }} --strip header
        env:
          OUTPUT: body.md

      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(changelog): update CHANGELOG.md for ${{ github.ref_name }}"
          file_pattern: 'CHANGELOG.md'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      # --- Create GitHub Release ---
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
